---
name: Module-Build-Convert
version: 0.42
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
abstract: Makefile.PL to Build.PL converter
license: perl
requires:
  Carp: 0
  Cwd: 0
  Data::Dumper: 0
  ExtUtils::MakeMaker: 0
  File::Basename: 0
  File::HomeDir: 0
  File::Slurp: 0
  File::Spec: 0
  Getopt::Long: 0
  IO::File: 0
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
build_requires:
  Test::More: 0
provides:
  Module::Build::Convert:
    file: lib/Module/Build/Convert.pm
    version: 0.42
generated_by: Module::Build version 0.2611
